import Image from "next/image"
import images from "@/images"

const Splash_screen_slider = () => {
    return (
        <div className="flex h-full  ">
            {/* <div className="flex h-screen whalf-r border"></div> */}
            <div className="">
                <logo-slider>
                    <div>
                        <Image
                            src={images.a}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.b}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.c}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.d}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.e}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.f}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.a}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.b}
                            alt=""
                            width={400}
                            height={100}
                        />
                    </div>

                    <div>
                    <Image
                            src={images.a}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.b}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.c}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.d}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.e}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.f}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.a}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.b}
                            alt=""
                            width={400}
                            height={100}
                        />
                    </div>
                </logo-slider>
            </div>
            <div className="">
                <logo-slider className="lslider">
                <div>
                        <Image
                            src={images.a}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.b}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.c}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.d}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.e}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.f}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.a}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.b}
                            alt=""
                            width={400}
                            height={100}
                        />
                    </div>

                    <div>
                    <Image
                            src={images.a}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.b}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.c}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.d}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.e}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.f}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.a}
                            alt=""
                            width={400}
                            height={100}
                        />
                        <Image
                            src={images.b}
                            alt=""
                            width={400}
                            height={100}
                        />
                    </div>
                </logo-slider>
            </div>
        </div>
    )
}

export default Splash_screen_slider